[2024-06-24T02:18:41.160+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T02:18:41.210+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_operator_2.load_parquet_to_postgres scheduled__2024-06-24T02:17:00+00:00 [queued]>
[2024-06-24T02:18:41.248+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_operator_2.load_parquet_to_postgres scheduled__2024-06-24T02:17:00+00:00 [queued]>
[2024-06-24T02:18:41.256+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-24T02:18:41.283+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_parquet_to_postgres> on 2024-06-24 02:17:00+00:00
[2024-06-24T02:18:41.333+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1413) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-24T02:18:41.342+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_2', 'load_parquet_to_postgres', 'scheduled__2024-06-24T02:17:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpdpsm3scr']
[2024-06-24T02:18:41.363+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask load_parquet_to_postgres
[2024-06-24T02:18:41.360+0000] {standard_task_runner.py:63} INFO - Started process 1447 to run task
[2024-06-24T02:18:41.606+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_operator_2.load_parquet_to_postgres scheduled__2024-06-24T02:17:00+00:00 [running]> on host 18d040e2d413
[2024-06-24T02:18:41.762+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_operator_2' AIRFLOW_CTX_TASK_ID='load_parquet_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T02:17:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-24T02:17:00+00:00'
[2024-06-24T02:18:41.766+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T02:18:41.835+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-24T02:18:41.837+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-24T02:18:41.839+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-24T02:18:41.839+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-24T02:18:41.840+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-24T02:18:41.884+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-24T02:18:41.888+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-24T02:18:41.893+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-24T02:18:41.903+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-24T02:18:41.929+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-24T02:18:41.930+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-24T02:18:41.931+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-24T02:18:41.926+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-24T02:18:41.931+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-24T02:18:41.955+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-24T02:18:41.964+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-06-24T02:18:51.939+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-06-24T02:18:51.963+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-24T02:18:51.969+0000] {process_utils.py:132} INFO - Sending 15 to group 1447. PIDs of all processes in the group: [1447]
[2024-06-24T02:18:51.971+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1447
[2024-06-24T02:18:52.514+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-24T02:18:52.814+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T02:18:53.027+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 43, in load_parquet_to_postgres
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 647, in __exit__
    self.shutdown(wait=True)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 238, in shutdown
    t.join()
  File "/usr/local/lib/python3.12/threading.py", line 1147, in join
    self._wait_for_tstate_lock()
  File "/usr/local/lib/python3.12/threading.py", line 1167, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-06-24T02:18:53.584+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_operator_2, task_id=load_parquet_to_postgres, run_id=scheduled__2024-06-24T02:17:00+00:00, execution_date=20240624T021700, start_date=20240624T021841, end_date=20240624T021853
[2024-06-24T02:18:54.615+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 40 for task load_parquet_to_postgres ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(postgres_operator_2, load_parquet_to_postgres, scheduled__2024-06-24T02:17:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'load_parquet_to_postgres', 'dag_id': 'postgres_operator_2', 'run_id': 'scheduled__2024-06-24T02:17:00+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 6, 24, 2, 18, 41, 217523, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 6, 24, 2, 18, 53, 579817, tzinfo=Timezone('UTC')), 'duration': 12}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 1447)
[2024-06-24T02:18:54.730+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1447, status='terminated', exitcode=1, started='02:18:40') (1447) terminated with exit code 1
